name: Benchmark v14

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: Install just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
        with:
          just-version: 1.35.0
      - name: Install hyperfine
        run: cargo install hyperfine
      - name: Run Hyperfine
        run: just benchmark
