name: Verify v14

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  build-matrix:
    name: Build matrix
    runs-on: ubuntu-latest
    outputs:
      build_matrix: ${{ steps.set-matrix.outputs.build_matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            .github/workflows/matrix.json
          sparse-checkout-cone-mode: false
      - id: set-matrix
        shell: bash
        run: |
          echo "build_matrix=$( cat .github/workflows/matrix.json | jq --monochrome-output --compact-output )" >> $GITHUB_OUTPUT

  lint-and-test:
    name: Lint and test (${{ matrix.build.NAME }})
    needs: build-matrix
    runs-on: ${{ matrix.build.OS }}
    strategy:
      fail-fast: true
      matrix:
        build: ${{ fromJson(needs.build-matrix.outputs.build_matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - name: Install pnpm
        run: npm install -g pnpm@latest
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.build.TARGET }}
          components: rustfmt, clippy
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: Install just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
        with:
          just-version: 1.35.0
      - name: Check cargo
        run: just check-cargo
      - name: Lint formatting
        run: just check-formatting
      - name: Lint clippy
        run: just check-clippy
      - name: Cargo test
        run: just test
