name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write # Required for OIDC

jobs:
  build-matrix:
    name: Build matrix
    runs-on: ubuntu-latest
    outputs:
      build_matrix: ${{ steps.set-matrix.outputs.build_matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            .github/workflows/matrix.json
          sparse-checkout-cone-mode: false
      - id: set-matrix
        shell: bash
        run: |
          echo "build_matrix=$( cat .github/workflows/matrix.json | jq --monochrome-output --compact-output )" >> $GITHUB_OUTPUT

  publish-npm-binaries:
    name: Publish npm binaries
    needs: build-matrix
    runs-on: ${{ matrix.build.OS }}
    strategy:
      fail-fast: true
      matrix:
        build: ${{ fromJson(needs.build-matrix.outputs.build_matrix) }}
    steps:
      - name: Debug workflow values
        shell: bash
        run: |
          echo "matrix.build.NAME   : ${{ matrix.build.NAME }}"
          echo "matrix.build.OS     : ${{ matrix.build.OS }}"
          echo "matrix.build.TARGET : ${{ matrix.build.TARGET }}"
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Node
        uses: ./.github/actions/setup-node
      - name: Set up Rust build
        uses: ./.github/actions/setup-rust-build
        with:
          target: ${{ matrix.build.TARGET }}
      - name: Build Rust binary
        uses: ./.github/actions/build-rust-binary
        with:
          target: ${{ matrix.build.TARGET }}
      - name: Publish rust binary package to npm
        shell: bash
        run: |
          just --dotenv-filename .env.${{ matrix.build.NAME }} create-npm-binary-package
          just --dotenv-filename .env.${{ matrix.build.NAME }} publish-npm-binary-package
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: syncpack-${{ matrix.build.TARGET }}
          path: target/${{ matrix.build.TARGET }}/release/syncpack

  publish-npm-base:
    name: Publish npm package
    needs: publish-npm-binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Node
        uses: ./.github/actions/setup-node
      - name: Install just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
        with:
          just-version: 1.35.0
      - name: Publish the package
        shell: bash
        run: |
          npm install
          just --dotenv-filename .env.linux-x64-glibc create-npm-root-package
          just --dotenv-filename .env.linux-x64-glibc publish-npm-root-package
